openapi: 3.1.1
info:
  title: Legends API
  version: "0.1.0"
servers:
  - url: http://localhost:1997
    description: Docker
security:
  - ApiToken: []

paths:
  # @todo

components:
  securitySchemes:
    ApiToken:
      type: apiKey
      in: header
      name: X-Authorization
