parameters:
  database_uri: '%env(DATABASE_URI)%'
  database_name: '%env(key:path:url:DATABASE_URI)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Legends\Game\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  Legends\Game\Infrastructure\Persistence\DatabaseClient:
    $databaseUri: '%database_uri%'
    $databaseName: '%database_name%'

  Legends\Game\Infrastructure\Exception\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 101 }

  Legends\Game\Infrastructure\Http\HttpExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 100 }

  ### > API

  Legends\Game\Infrastructure\Http\World\MoveToLocation\MoveToLocationAPI:
    public: true

  ### < API
