name: PHP CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app
        run: docker compose build

      - name: Validate composer.json and composer.lock
        run: docker compose run --rm app sh -lc 'composer validate'

      - name: Install dependencies
        run: docker compose run --rm app sh -lc 'composer install --prefer-dist --no-progress --no-suggest'

      - name: Run PHPUnit tests
        run: docker compose run --rm app sh -lc 'XDEBUG_MODE=coverage ./vendor/bin/phpunit --testdox --coverage-text --colors=never'
